version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    errcheck:
      exclude-functions:
        - (*database/sql.DB).Close
        - (github.com/jackc/pgx/v5.Tx).Rollback
        - (*go.uber.org/zap.Logger).Sync
        - (*github.com/segmentio/kafka-go.Reader).Close

formatters:
  enable:
    - gofmt
    - goimports
