apiVersion: v1
kind: Service
metadata:
  name: warehouse-controller
  namespace: warehouse
  labels:
    app.kubernetes.io/name: warehouse-controller
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: warehouse-controller
  ports:
    - name: http
      port: 8080
      targetPort: http
