apiVersion: v1
kind: ConfigMap
metadata:
  name: warehouse-config
  namespace: warehouse
  labels:
    app.kubernetes.io/name: warehouse-controller
data:
  HTTP_PORT: "8080"
  LOG_LEVEL: "info"
  ACCESS_TTL: "15m"
  REFRESH_TTL: "168h"
  REDIS_URL: "redis://warehouse-redis-master:6379/0"
