apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: warehouse

resources:
  - namespace.yaml
  - configmap.yaml
  - kafka.yaml
  - app-deployment.yaml
  - app-service.yaml
  - consumer-deployment.yaml
  - ingress.yaml
