// Code generated by mockery. DO NOT EDIT.

package handlermock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	service "warehouse-controller/internal/service"
)

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// IssuePair provides a mock function with given fields: ctx
func (_m *MockAuthService) IssuePair(ctx context.Context) (service.TokenPair, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for IssuePair")
	}

	var r0 service.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (service.TokenPair, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) service.TokenPair); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(service.TokenPair)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_IssuePair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssuePair'
type MockAuthService_IssuePair_Call struct {
	*mock.Call
}

// IssuePair is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAuthService_Expecter) IssuePair(ctx interface{}) *MockAuthService_IssuePair_Call {
	return &MockAuthService_IssuePair_Call{Call: _e.mock.On("IssuePair", ctx)}
}

func (_c *MockAuthService_IssuePair_Call) Run(run func(ctx context.Context)) *MockAuthService_IssuePair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAuthService_IssuePair_Call) Return(_a0 service.TokenPair, _a1 error) *MockAuthService_IssuePair_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_IssuePair_Call) RunAndReturn(run func(context.Context) (service.TokenPair, error)) *MockAuthService_IssuePair_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function with given fields: ctx, refreshToken
func (_m *MockAuthService) Refresh(ctx context.Context, refreshToken string) (service.TokenPair, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 service.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (service.TokenPair, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) service.TokenPair); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Get(0).(service.TokenPair)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockAuthService_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuthService_Expecter) Refresh(ctx interface{}, refreshToken interface{}) *MockAuthService_Refresh_Call {
	return &MockAuthService_Refresh_Call{Call: _e.mock.On("Refresh", ctx, refreshToken)}
}

func (_c *MockAuthService_Refresh_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthService_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_Refresh_Call) Return(_a0 service.TokenPair, _a1 error) *MockAuthService_Refresh_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_Refresh_Call) RunAndReturn(run func(context.Context, string) (service.TokenPair, error)) *MockAuthService_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
