// Code generated by mockery. DO NOT EDIT.

package handlermock

import (
	context "context"
	domain "warehouse-controller/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockWarehouseService is an autogenerated mock type for the WarehouseService type
type MockWarehouseService struct {
	mock.Mock
}

type MockWarehouseService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWarehouseService) EXPECT() *MockWarehouseService_Expecter {
	return &MockWarehouseService_Expecter{mock: &_m.Mock}
}

// CreateProduct provides a mock function with given fields: ctx, req
func (_m *MockWarehouseService) CreateProduct(ctx context.Context, req domain.CreateProductParams) (int64, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateProductParams) (int64, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateProductParams) int64); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CreateProductParams) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWarehouseService_CreateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProduct'
type MockWarehouseService_CreateProduct_Call struct {
	*mock.Call
}

// CreateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.CreateProductParams
func (_e *MockWarehouseService_Expecter) CreateProduct(ctx interface{}, req interface{}) *MockWarehouseService_CreateProduct_Call {
	return &MockWarehouseService_CreateProduct_Call{Call: _e.mock.On("CreateProduct", ctx, req)}
}

func (_c *MockWarehouseService_CreateProduct_Call) Run(run func(ctx context.Context, req domain.CreateProductParams)) *MockWarehouseService_CreateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.CreateProductParams))
	})
	return _c
}

func (_c *MockWarehouseService_CreateProduct_Call) Return(_a0 int64, _a1 error) *MockWarehouseService_CreateProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWarehouseService_CreateProduct_Call) RunAndReturn(run func(context.Context, domain.CreateProductParams) (int64, error)) *MockWarehouseService_CreateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProduct provides a mock function with given fields: ctx, req
func (_m *MockWarehouseService) DeleteProduct(ctx context.Context, req domain.DeleteProductParams) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.DeleteProductParams) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWarehouseService_DeleteProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProduct'
type MockWarehouseService_DeleteProduct_Call struct {
	*mock.Call
}

// DeleteProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.DeleteProductParams
func (_e *MockWarehouseService_Expecter) DeleteProduct(ctx interface{}, req interface{}) *MockWarehouseService_DeleteProduct_Call {
	return &MockWarehouseService_DeleteProduct_Call{Call: _e.mock.On("DeleteProduct", ctx, req)}
}

func (_c *MockWarehouseService_DeleteProduct_Call) Run(run func(ctx context.Context, req domain.DeleteProductParams)) *MockWarehouseService_DeleteProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.DeleteProductParams))
	})
	return _c
}

func (_c *MockWarehouseService_DeleteProduct_Call) Return(_a0 error) *MockWarehouseService_DeleteProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWarehouseService_DeleteProduct_Call) RunAndReturn(run func(context.Context, domain.DeleteProductParams) error) *MockWarehouseService_DeleteProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductByID provides a mock function with given fields: ctx, req
func (_m *MockWarehouseService) GetProductByID(ctx context.Context, req domain.GetProductParams) (*domain.Product, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByID")
	}

	var r0 *domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.GetProductParams) (*domain.Product, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.GetProductParams) *domain.Product); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.GetProductParams) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWarehouseService_GetProductByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductByID'
type MockWarehouseService_GetProductByID_Call struct {
	*mock.Call
}

// GetProductByID is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.GetProductParams
func (_e *MockWarehouseService_Expecter) GetProductByID(ctx interface{}, req interface{}) *MockWarehouseService_GetProductByID_Call {
	return &MockWarehouseService_GetProductByID_Call{Call: _e.mock.On("GetProductByID", ctx, req)}
}

func (_c *MockWarehouseService_GetProductByID_Call) Run(run func(ctx context.Context, req domain.GetProductParams)) *MockWarehouseService_GetProductByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.GetProductParams))
	})
	return _c
}

func (_c *MockWarehouseService_GetProductByID_Call) Return(_a0 *domain.Product, _a1 error) *MockWarehouseService_GetProductByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWarehouseService_GetProductByID_Call) RunAndReturn(run func(context.Context, domain.GetProductParams) (*domain.Product, error)) *MockWarehouseService_GetProductByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListProducts provides a mock function with given fields: ctx, req
func (_m *MockWarehouseService) ListProducts(ctx context.Context, req domain.ListProductsParams) ([]domain.Product, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListProducts")
	}

	var r0 []domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ListProductsParams) ([]domain.Product, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ListProductsParams) []domain.Product); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ListProductsParams) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWarehouseService_ListProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProducts'
type MockWarehouseService_ListProducts_Call struct {
	*mock.Call
}

// ListProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.ListProductsParams
func (_e *MockWarehouseService_Expecter) ListProducts(ctx interface{}, req interface{}) *MockWarehouseService_ListProducts_Call {
	return &MockWarehouseService_ListProducts_Call{Call: _e.mock.On("ListProducts", ctx, req)}
}

func (_c *MockWarehouseService_ListProducts_Call) Run(run func(ctx context.Context, req domain.ListProductsParams)) *MockWarehouseService_ListProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ListProductsParams))
	})
	return _c
}

func (_c *MockWarehouseService_ListProducts_Call) Return(_a0 []domain.Product, _a1 error) *MockWarehouseService_ListProducts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWarehouseService_ListProducts_Call) RunAndReturn(run func(context.Context, domain.ListProductsParams) ([]domain.Product, error)) *MockWarehouseService_ListProducts_Call {
	_c.Call.Return(run)
	return _c
}

// PatchProduct provides a mock function with given fields: ctx, req
func (_m *MockWarehouseService) PatchProduct(ctx context.Context, req domain.PatchProductParams) (*domain.Product, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for PatchProduct")
	}

	var r0 *domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PatchProductParams) (*domain.Product, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PatchProductParams) *domain.Product); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PatchProductParams) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWarehouseService_PatchProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchProduct'
type MockWarehouseService_PatchProduct_Call struct {
	*mock.Call
}

// PatchProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.PatchProductParams
func (_e *MockWarehouseService_Expecter) PatchProduct(ctx interface{}, req interface{}) *MockWarehouseService_PatchProduct_Call {
	return &MockWarehouseService_PatchProduct_Call{Call: _e.mock.On("PatchProduct", ctx, req)}
}

func (_c *MockWarehouseService_PatchProduct_Call) Run(run func(ctx context.Context, req domain.PatchProductParams)) *MockWarehouseService_PatchProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.PatchProductParams))
	})
	return _c
}

func (_c *MockWarehouseService_PatchProduct_Call) Return(_a0 *domain.Product, _a1 error) *MockWarehouseService_PatchProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWarehouseService_PatchProduct_Call) RunAndReturn(run func(context.Context, domain.PatchProductParams) (*domain.Product, error)) *MockWarehouseService_PatchProduct_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreProduct provides a mock function with given fields: ctx, req
func (_m *MockWarehouseService) RestoreProduct(ctx context.Context, req domain.RestoreProductParams) (*domain.Product, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RestoreProduct")
	}

	var r0 *domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.RestoreProductParams) (*domain.Product, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.RestoreProductParams) *domain.Product); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.RestoreProductParams) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWarehouseService_RestoreProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreProduct'
type MockWarehouseService_RestoreProduct_Call struct {
	*mock.Call
}

// RestoreProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.RestoreProductParams
func (_e *MockWarehouseService_Expecter) RestoreProduct(ctx interface{}, req interface{}) *MockWarehouseService_RestoreProduct_Call {
	return &MockWarehouseService_RestoreProduct_Call{Call: _e.mock.On("RestoreProduct", ctx, req)}
}

func (_c *MockWarehouseService_RestoreProduct_Call) Run(run func(ctx context.Context, req domain.RestoreProductParams)) *MockWarehouseService_RestoreProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.RestoreProductParams))
	})
	return _c
}

func (_c *MockWarehouseService_RestoreProduct_Call) Return(_a0 *domain.Product, _a1 error) *MockWarehouseService_RestoreProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWarehouseService_RestoreProduct_Call) RunAndReturn(run func(context.Context, domain.RestoreProductParams) (*domain.Product, error)) *MockWarehouseService_RestoreProduct_Call {
	_c.Call.Return(run)
	return _c
}

// SearchProducts provides a mock function with given fields: ctx, req
func (_m *MockWarehouseService) SearchProducts(ctx context.Context, req domain.SearchProductsParams) ([]domain.Product, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SearchProducts")
	}

	var r0 []domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.SearchProductsParams) ([]domain.Product, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.SearchProductsParams) []domain.Product); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.SearchProductsParams) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWarehouseService_SearchProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchProducts'
type MockWarehouseService_SearchProducts_Call struct {
	*mock.Call
}

// SearchProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.SearchProductsParams
func (_e *MockWarehouseService_Expecter) SearchProducts(ctx interface{}, req interface{}) *MockWarehouseService_SearchProducts_Call {
	return &MockWarehouseService_SearchProducts_Call{Call: _e.mock.On("SearchProducts", ctx, req)}
}

func (_c *MockWarehouseService_SearchProducts_Call) Run(run func(ctx context.Context, req domain.SearchProductsParams)) *MockWarehouseService_SearchProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.SearchProductsParams))
	})
	return _c
}

func (_c *MockWarehouseService_SearchProducts_Call) Return(_a0 []domain.Product, _a1 error) *MockWarehouseService_SearchProducts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWarehouseService_SearchProducts_Call) RunAndReturn(run func(context.Context, domain.SearchProductsParams) ([]domain.Product, error)) *MockWarehouseService_SearchProducts_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWarehouseService creates a new instance of MockWarehouseService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWarehouseService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWarehouseService {
	mock := &MockWarehouseService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
