// Code generated by mockery. DO NOT EDIT.

package repomock

import (
	context "context"
	dbmodel "warehouse-controller/internal/repo/dbmodel"

	mock "github.com/stretchr/testify/mock"
)

// MockProductRepository is an autogenerated mock type for the ProductRepository type
type MockProductRepository struct {
	mock.Mock
}

type MockProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductRepository) EXPECT() *MockProductRepository_Expecter {
	return &MockProductRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, product
func (_m *MockProductRepository) Create(ctx context.Context, product *dbmodel.Product) (int64, error) {
	ret := _m.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dbmodel.Product) (int64, error)); ok {
		return rf(ctx, product)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dbmodel.Product) int64); ok {
		r0 = rf(ctx, product)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dbmodel.Product) error); ok {
		r1 = rf(ctx, product)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProductRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - product *dbmodel.Product
func (_e *MockProductRepository_Expecter) Create(ctx interface{}, product interface{}) *MockProductRepository_Create_Call {
	return &MockProductRepository_Create_Call{Call: _e.mock.On("Create", ctx, product)}
}

func (_c *MockProductRepository_Create_Call) Run(run func(ctx context.Context, product *dbmodel.Product)) *MockProductRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dbmodel.Product))
	})
	return _c
}

func (_c *MockProductRepository_Create_Call) Return(_a0 int64, _a1 error) *MockProductRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_Create_Call) RunAndReturn(run func(context.Context, *dbmodel.Product) (int64, error)) *MockProductRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockProductRepository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProductRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockProductRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockProductRepository_Delete_Call {
	return &MockProductRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockProductRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockProductRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockProductRepository_Delete_Call) Return(_a0 error) *MockProductRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *MockProductRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockProductRepository) GetByID(ctx context.Context, id int64) (*dbmodel.Product, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *dbmodel.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*dbmodel.Product, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *dbmodel.Product); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dbmodel.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockProductRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockProductRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockProductRepository_GetByID_Call {
	return &MockProductRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockProductRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockProductRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockProductRepository_GetByID_Call) Return(_a0 *dbmodel.Product, _a1 error) *MockProductRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*dbmodel.Product, error)) *MockProductRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *MockProductRepository) List(ctx context.Context, limit int32, offset int32) ([]dbmodel.Product, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []dbmodel.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) ([]dbmodel.Product, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int32) []dbmodel.Product); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dbmodel.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int32) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockProductRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int32
//   - offset int32
func (_e *MockProductRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *MockProductRepository_List_Call {
	return &MockProductRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *MockProductRepository_List_Call) Run(run func(ctx context.Context, limit int32, offset int32)) *MockProductRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(int32))
	})
	return _c
}

func (_c *MockProductRepository_List_Call) Return(_a0 []dbmodel.Product, _a1 error) *MockProductRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_List_Call) RunAndReturn(run func(context.Context, int32, int32) ([]dbmodel.Product, error)) *MockProductRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: ctx, id, patch
func (_m *MockProductRepository) Patch(ctx context.Context, id int64, patch dbmodel.ProductPatch) (*dbmodel.Product, error) {
	ret := _m.Called(ctx, id, patch)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 *dbmodel.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, dbmodel.ProductPatch) (*dbmodel.Product, error)); ok {
		return rf(ctx, id, patch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, dbmodel.ProductPatch) *dbmodel.Product); ok {
		r0 = rf(ctx, id, patch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dbmodel.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, dbmodel.ProductPatch) error); ok {
		r1 = rf(ctx, id, patch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type MockProductRepository_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - patch dbmodel.ProductPatch
func (_e *MockProductRepository_Expecter) Patch(ctx interface{}, id interface{}, patch interface{}) *MockProductRepository_Patch_Call {
	return &MockProductRepository_Patch_Call{Call: _e.mock.On("Patch", ctx, id, patch)}
}

func (_c *MockProductRepository_Patch_Call) Run(run func(ctx context.Context, id int64, patch dbmodel.ProductPatch)) *MockProductRepository_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(dbmodel.ProductPatch))
	})
	return _c
}

func (_c *MockProductRepository_Patch_Call) Return(_a0 *dbmodel.Product, _a1 error) *MockProductRepository_Patch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_Patch_Call) RunAndReturn(run func(context.Context, int64, dbmodel.ProductPatch) (*dbmodel.Product, error)) *MockProductRepository_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function with given fields: ctx, id
func (_m *MockProductRepository) Restore(ctx context.Context, id int64) (*dbmodel.Product, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 *dbmodel.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*dbmodel.Product, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *dbmodel.Product); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dbmodel.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type MockProductRepository_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockProductRepository_Expecter) Restore(ctx interface{}, id interface{}) *MockProductRepository_Restore_Call {
	return &MockProductRepository_Restore_Call{Call: _e.mock.On("Restore", ctx, id)}
}

func (_c *MockProductRepository_Restore_Call) Run(run func(ctx context.Context, id int64)) *MockProductRepository_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockProductRepository_Restore_Call) Return(_a0 *dbmodel.Product, _a1 error) *MockProductRepository_Restore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_Restore_Call) RunAndReturn(run func(context.Context, int64) (*dbmodel.Product, error)) *MockProductRepository_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, filter
func (_m *MockProductRepository) Search(ctx context.Context, filter dbmodel.ProductFilter) ([]dbmodel.Product, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []dbmodel.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dbmodel.ProductFilter) ([]dbmodel.Product, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dbmodel.ProductFilter) []dbmodel.Product); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dbmodel.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dbmodel.ProductFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockProductRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - filter dbmodel.ProductFilter
func (_e *MockProductRepository_Expecter) Search(ctx interface{}, filter interface{}) *MockProductRepository_Search_Call {
	return &MockProductRepository_Search_Call{Call: _e.mock.On("Search", ctx, filter)}
}

func (_c *MockProductRepository_Search_Call) Run(run func(ctx context.Context, filter dbmodel.ProductFilter)) *MockProductRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dbmodel.ProductFilter))
	})
	return _c
}

func (_c *MockProductRepository_Search_Call) Return(_a0 []dbmodel.Product, _a1 error) *MockProductRepository_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_Search_Call) RunAndReturn(run func(context.Context, dbmodel.ProductFilter) ([]dbmodel.Product, error)) *MockProductRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductRepository creates a new instance of MockProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductRepository {
	mock := &MockProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
