// Code generated by mockery. DO NOT EDIT.

package middlewaremock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAccessValidator is an autogenerated mock type for the AccessValidator type
type MockAccessValidator struct {
	mock.Mock
}

type MockAccessValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccessValidator) EXPECT() *MockAccessValidator_Expecter {
	return &MockAccessValidator_Expecter{mock: &_m.Mock}
}

// ValidateAccess provides a mock function with given fields: ctx, accessToken
func (_m *MockAccessValidator) ValidateAccess(ctx context.Context, accessToken string) (string, error) {
	ret := _m.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccess")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, accessToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, accessToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccessValidator_ValidateAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccess'
type MockAccessValidator_ValidateAccess_Call struct {
	*mock.Call
}

// ValidateAccess is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *MockAccessValidator_Expecter) ValidateAccess(ctx interface{}, accessToken interface{}) *MockAccessValidator_ValidateAccess_Call {
	return &MockAccessValidator_ValidateAccess_Call{Call: _e.mock.On("ValidateAccess", ctx, accessToken)}
}

func (_c *MockAccessValidator_ValidateAccess_Call) Run(run func(ctx context.Context, accessToken string)) *MockAccessValidator_ValidateAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAccessValidator_ValidateAccess_Call) Return(_a0 string, _a1 error) *MockAccessValidator_ValidateAccess_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccessValidator_ValidateAccess_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockAccessValidator_ValidateAccess_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccessValidator creates a new instance of MockAccessValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccessValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccessValidator {
	mock := &MockAccessValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
