// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    product_name,
    manufacturer,
    category,
    count,
    price
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateProductParams struct {
	ProductName  string
	Manufacturer string
	Category     string
	Count        int32
	Price        int64
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (int64, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ProductName,
		arg.Manufacturer,
		arg.Category,
		arg.Count,
		arg.Price,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteProduct = `-- name: DeleteProduct :exec
UPDATE products
SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, created_at, updated_at, deleted_at, product_name, manufacturer, category, count, price
FROM products
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetProductByID(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProductName,
		&i.Manufacturer,
		&i.Category,
		&i.Count,
		&i.Price,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, created_at, updated_at, deleted_at, product_name, manufacturer, category, count, price
FROM products
WHERE deleted_at IS NULL
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProductName,
			&i.Manufacturer,
			&i.Category,
			&i.Count,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchProduct = `-- name: PatchProduct :one
UPDATE products
SET
    product_name = COALESCE($1::text, product_name),
    manufacturer = COALESCE($2::text, manufacturer),
    category = COALESCE($3::text, category),
    count = COALESCE($4::integer, count),
    price = COALESCE($5::bigint, price),
    updated_at = NOW()
WHERE id = $6
  AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, product_name, manufacturer, category, count, price
`

type PatchProductParams struct {
	ProductName  pgtype.Text
	Manufacturer pgtype.Text
	Category     pgtype.Text
	Count        pgtype.Int4
	Price        pgtype.Int8
	ID           int64
}

func (q *Queries) PatchProduct(ctx context.Context, arg PatchProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, patchProduct,
		arg.ProductName,
		arg.Manufacturer,
		arg.Category,
		arg.Count,
		arg.Price,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProductName,
		&i.Manufacturer,
		&i.Category,
		&i.Count,
		&i.Price,
	)
	return i, err
}

const restoreProduct = `-- name: RestoreProduct :one
UPDATE products
SET
    deleted_at = NULL,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NOT NULL
RETURNING id, created_at, updated_at, deleted_at, product_name, manufacturer, category, count, price
`

func (q *Queries) RestoreProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, restoreProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProductName,
		&i.Manufacturer,
		&i.Category,
		&i.Count,
		&i.Price,
	)
	return i, err
}

const searchProducts = `-- name: SearchProducts :many
SELECT id, created_at, updated_at, deleted_at, product_name, manufacturer, category, count, price
FROM products
WHERE deleted_at IS NULL
  AND (
    $1::text IS NULL
    OR product_name ILIKE '%' || $1::text || '%'
  )
  AND (
    $2::text IS NULL
    OR manufacturer = $2::text
  )
  AND (
    $3::text IS NULL
    OR category = $3::text
  )
  AND (
    $4::bigint IS NULL
    OR price >= $4::bigint
  )
  AND (
    $5::bigint IS NULL
    OR price <= $5::bigint
  )
ORDER BY id DESC
LIMIT $7::int
OFFSET $6::int
`

type SearchProductsParams struct {
	ProductName  pgtype.Text
	Manufacturer pgtype.Text
	Category     pgtype.Text
	MinPrice     pgtype.Int8
	MaxPrice     pgtype.Int8
	Offset       int32
	Limit        int32
}

func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, searchProducts,
		arg.ProductName,
		arg.Manufacturer,
		arg.Category,
		arg.MinPrice,
		arg.MaxPrice,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProductName,
			&i.Manufacturer,
			&i.Category,
			&i.Count,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
